version: '3'

services:
  ranksystem:
    container_name: ts-ranksystem
    image: bl4ckbirb/ts-ranksystem-docker:latest
    restart: always
    ports:
      - 8443:80
    volumes:
      - ./www/:/var/www/html/