version: '3'

services:
  ranksystem:
    container_name: ts-ranksystem
    image: ghcr.io/bl4ckbirb/ts-ranksystem-docker:main
    restart: always
    ports:
      - 8443:80
    volumes:
      - ./www/:/var/www/html/
      - ./apache2/:/host/apache2/
    #environment:
      #- APACHE_PORT=80
      #- APACHE_PORT_SSL=443
